### PR TITLE
Linux 4.9.30 krun dev

### LINKED ISSUE #5: Port to 4.9.30 to track Debian 9.1.0.

### PR DESCRIPTION
**Pull request by vext01**
This is the changes from our 4.9.0 kernel forward ported to 4.9.30 to match debian 9.1.

This is the result of one `git merge` and one commit to update the version numbers.

I'm not sure if we want to squash the merge or not. What do you think?

Tested on my local Linux machine. Works fine.

Fixes #5

### CODE REVIEW

**Comment by vext01** [comment]
I also have binary packages for this kernel. I'm going to raise an issue to discuss distribution.

**Comment by vext01** [comment]
This is ready for review independently of #9.

**Comment by ltratt** [comment]
Sorry, I completely missed this one!

We shouldn't squash our old commits IMHO: that would lose useful history. If you want to squash anything from the merge onwards, that's fine. Any thoughts?

**Comment by vext01** [comment]
There's only one commit after the merge, so no need to squash.

**Comment by ltratt** [comment]
So merge as-is?

**Comment by vext01** [comment]
Correct.

**Pull request merged**
