### PR TITLE
Krun landing branch.

### PR DESCRIPTION
**Pull request by vext01**
Here's a landing branch for this repo.

It simply lists the branches that contain modified versions of the Linux kernel.

OK?

### CODE REVIEW

**Comment by vext01** [comment]
To see the README rendered:
https://github.com/softdevteam/krun-linux-kernel/blob/krun-default-initial/README.md

**Comment by ltratt** [comment]
Unless you want to add anything else, I think this is ready for squashing.

**Comment by vext01** [comment]
I updated the URL and squashed.

**Comment by ltratt** [comment]
OK to merge then?

**Comment by vext01** [comment]
go ahead.

**Pull request merged**
